spring:
  application:
    name: diplom
  config:
    import: optional:file:./util/.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/diplom}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          arduinoClient:
            url: ${ARDUINO_URL:http://192.168.0.131}
            error-decoder: com.netharus.exceptions.decoder.CustomErrorDecoder
  web:
    resources:
      add-mappings: true

server:
  port: ${SERVER_PORT:8080}
logging:
  level:
    org.springframework.web: DEBUG