spring:
  application:
    name: diplom
  config:
    import: optional:file:./util/.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          arduinoClient:
            url: ${ARDUINO_URL}
            error-decoder: com.netharus.exceptions.decoder.CustomErrorDecoder

server:
  port: ${SERVER_PORT}
